# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Emmanuel Abioye
title: BSc. Electrical Engineering Student
email: eabioye@ualberta.ca
website: eabioye.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  eabioye
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: eabioye
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Emmanuel and I'm a final year student at the University of Albera studying Electrical Engineering. I've studied courses and done projects related to circuits, microprocessors, electronic devices, embedded system design, control systems, and analog electronics. I am proficient in C, MATLAB, and circuit simulation tools like LTspice. My goal is to apply these skills in a practical setting and learn many more things

  I have taken courses on the following topics: <mark>Control Systems</mark> , <mark>Machine Learning and Data Analysis</mark>, <mark>Wireless Communications</mark>, and <mark>Power Electronics</mark>.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Smart Home Controller Hub
        description: |
          - Collaborated with team members to develop a sustainable household device prototype under 12 hours as part of a Hardware Design competition, earning a top 4 placement
          - Designed featuring the ATMega328p, a DHT11 for humidity and temperature, an LCD, PS2 Analog stick, a motion sensor, LEDs and buttons
          - Programmed to display menus for general system information, temperatue control, and motion detection alert using the LED
         
        #link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Nanoprecise Sci. Corp
        link: nanoprecise.io
        # link_text: boringcompany.com
        sub_title: Hardware Assembler
        caption: October 2024 - January 2025
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            - Assembled sensor units and other hardware according to supervisor's detailed instructions
            - Performed routine testing and calibration of assembled sensors
            - Inspected components to ensure quality standards are met
            - Assisted in fulfillment, packing, or any other tasks as instructed by lead
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Alberta
        caption: 2021 - 2025
        sub_title: BSc Electrical Engineering
 #       quote: >
 #         Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at the UofA I learnt many key skills such as collaboration, complex problem solving, research and working to tight deadlines. 
          I spent my free time as a voluntary member of the *Autonomous Robotic Vehicle Project* taking on tasks such as crimping, soldering and labelling of obstacles and targets for the vehicle navigation.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Some of my interests and hobbies are:
      - Playing soccer occasionally
      - Gaming
      - Building LEGO
      
#      Look at this cool image  
#      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
