# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Emmanuel Abioye
title: Electrical Engineering Student
email: eabloye@ualberta.ca
website: linkedin.com/in/eabloye/

# Dark Mode (true/false/never)
darkmode: false

# Social links
linkedin_username: eabloye

# About Section
about_profile_image: images/profile.jpg
about_content: |
  Electrical Engineering student at the University of Alberta (Expected Graduation: 2025). Passionate about embedded systems, analog electronics, and sustainable hardware design. Proven track record in collaborative projects, technical prototyping, and hands-on assembly work.

  Technical Skills: <mark>Embedded C</mark>, <mark>Altium Designer</mark>, <mark>MPLAB X IDE</mark>, <mark>PCB Design</mark>, <mark>Analog/Digital Circuit Simulation</mark>

content:
  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: Smart Home Controller Hub (E2C2 Competition)
        caption: Sep 2024 - Sep 2024 | Top 4 out of 20 teams
        description: |
          - Designed a prototype using ATmega328p, DHT11 sensor, LCD, and motion sensors.
          - Programmed menu navigation and LED alerts for temperature/motion detection.
          - Achieved high scores in reliability and technical presentation.

      - layout: top-middle
        title: Differential Amplifier – Analog Electronics
        caption: Jan 2024 - Apr 2024 | University of Alberta
        description: |
          - Built a differential amplifier with long-tailed resistor and current mirrors.
          - Simulated gains (43dB Differential Mode, 39dB CMRR) and validated with experimental models.
          - Analyzed DC bias voltages, currents, and common-mode rejection ratios.

      - layout: top-middle
        title: Timer-Stopwatch (Embedded Devices)
        caption: Sep 2023 - Dec 2023 | Graded 89%
        description: |
          - Developed a C-based timer/stopwatch using ATmega328 and ADC for menu navigation.
          - Collaborated on proposals and cost sheets; demonstrated interrupts for timekeeping.

  - title: Experience
    layout: list
    content:
      - layout: left
        title: Nanoprecise Sci Corp
        sub_title: Mechanical Assembler (Part-Time)
        caption: Oct 2024 – Jan 2025
        description: |
          - Assembled and calibrated sensor units, ensuring quality standards.
          - Collaborated with engineers to optimize assembly processes.
          - Assisted in fulfillment and testing tasks.

      - layout: left
        title: Autonomous Robotic Vehicle Project
        sub_title: Electrical Team Member (Volunteer)
        caption: Jun 2024 – Dec 2024
        description: |
          - Soldered components and labeled robot run data.
          - Reviewed PCB designs using Altium Designer.

  - title: Education
    layout: list
    content:
      - layout: left
        title: University of Alberta
        sub_title: BSc Electrical Engineering
        caption: Expected 2025
        description: |
          Relevant Coursework: 
          - Power Electronics, Data Analysis & Machine Learning, Control Systems
          - Digital Communications, Multimedia Signal Processing, Data Communication Networks

  - title: Technical Expertise
    layout: text
    content: |
      **Tools & Technologies:**  
      ATmega328p, DHT11 Sensors, MPLAB X IDE, AVR-GCC, Altium Designer, Oscilloscopes  
      
      **Core Competencies:**  
      Circuit Design, Embedded Programming, Sensor Integration, Technical Documentation

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme
plugins:
  - jekyll-seo-tag
